config/routes.rb
Rails.application.routes.draw do
  get 'favorites/crate'

  get 'sessions/new'

  resources :contributions
  resources :users
  resources :sessions
  resources :favorites

  root  'sessions#new'
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  mount_uploader :file, FileUploader
  
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  
  enum category:{
    サービス: 1,
    商品:2,
    イベント: 3,
    セミナー説明: 4,
    協賛: 5,
    商品開発: 6,
    データ分析: 7,
    システム開発: 8,
    その他: 9
  }

  validates :title,  presence: true
  validates :overview, presence: true
  
end

  # config.i18n.load_path += Dir[Rails.root.join('config', 'locales', '**', '*.{rb,yml}').to_s]

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :contribution
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  has_many :favorites, dependent: :destroy
  has_many :contributions, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :set_contribution, only: [:show, :edit, :update, :destroy]
  

  # GET /contributions
  # GET /contributions.json
  def index
    # @contributions = Contribution.all
    
    @search = Contribution.search(params[:q])
    @result = @search.result
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @result
      }
    end  
  end

  # GET /contributions/1
  # GET /contributions/1.json
  def show
    @favorite = current_user.favorites.find_by(contribution_id: @contribution.id)
  end

  # GET /contributions/new
  def new
    @contribution = Contribution.new
  end

  # GET /contributions/1/edit
  def edit
  end

  # POST /contributions
  # POST /contributions.json
  def create
    @contribution = current_user.contributions.build(contribution_params)
    respond_to do |format|
      
      if @contribution.save
        format.html { redirect_to contributions_path, notice: '新規投稿が完了しました。' }
        format.json { render :show, status: :created, location: @contribution }
      else
        format.html { render :new }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contributions/1
  # PATCH/PUT /contributions/1.json
  def update
    respond_to do |format|
      if @contribution.update(contribution_params)
        format.html { redirect_to @contribution, notice: '更新しました。' }
        format.json { render :show, status: :ok, location: @contribution }
      else
        format.html { render :edit }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @contribution.destroy
    respond_to do |format|
      format.html { redirect_to contributions_url, notice: '投稿を削除しました。' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    
    def contribution_params
      params.require(:contribution).permit(:title, :overview, :file, :modified, :category)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: :destroy

  def index
    @favorites = current_user.favorites
  end  

  def create
    @favorite = current_user.favorites.create(contribution_id: params[:contribution_id])
    if @favorite.save
      WatchlistNoticeMailer.watchlist_notice(@favorite).deliver
      redirect_to contributions_url, notice: "#{@favorite.contribution.user.name}さんの提案書をお気に入り登録しました"
    else
      render :new
    end
  end

  def destroy
    current_user.favorites.find_by(contribution_id: params[:contribution_id]).destroy
    redirect_to contributions_url, notice: "#{@favorite.contribution.user.name}さんの提案書をお気に入り解除しました"
  end
  
  private
  
  def set_favorite
    @favorite = Favorite.find_by(contribution_id: params[:contribution_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end  
    
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
  
  def show
    @user = User.find(params[:id])
    @contributions = @user.contributions
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
     def current_user
       @current_user ||= User.find_by(id: session[:user_id])
     end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contributions/_form.html.erb
<%= form_with(model: contribution, local: true) do |form| %>
 <% if @contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= @contribution.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @contribution.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
<body>
    <div class="field">
      <%= form.label :タイトル %>
      <%= form.text_field :title, id: :contribution_title %>
    </div>
  
    <div class="field">
      <%= form.label :概要 %>
      <%= form.text_area :overview, id: :contribution_overview %>
    </div>
  
    <div class="field">
      <%= form.label :カテゴリ %>
      <%= select :contribution, :category, Contribution.categories.keys %>
    </div>
  
    <div class="field">
      <%= form.label :最終更新日 %>
      <%= form.date_select :modified, id: :contribution_modified %>
    </div>
    
    <div class="field">
      <%= form.label :データファイル %>
      <%= form.file_field :file, id: :feed_file %>
      <%= form.hidden_field :file_cache %>
    </div>
    
    <div class="actions">
      <%= form.submit %>
    </div>
    
    <% end %>
</body>

app/views/contributions/edit.html.erb
<h1>Editing Contribution</h1>

<%= render 'form', contribution: @contribution %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<p id="notice"></p>

<div class="title_back_edit">  
  <h1>投稿提案書一覧</h1>
</div>

<div class ="search_form_for">
  <%= search_form_for @search do |f| %>
    <!--<%= f.label :title_cont, 'タイトル' %>-->
    <%= f.text_field :title_cont %>
    <%= f.submit 'タイトル検索' %>
    
    <!--<%= f.label :overview_cont, '概要' %>-->
    <%= f.text_field :overview_cont %>
    <%= f.submit '概要検索' %>
  <% end %>
</div>

<table class="table table-hover" border="1" bordercolor="#D8D8D8">
  <tr>
      <th>投稿者</th>
      <th>タイトル</th>
      <th>概要</th>
      <th>カテゴリ</th>
      <th>最終更新日</th>
  </tr>

  <tr>
    <% @result.each do |contribution| %>
      <td><%= contribution.user.name %></td>
      <td><%= contribution.title %></td>
      <td><%= contribution.overview %></td>
      <td><%= contribution.category %></td>
      <td><%= contribution.modified %></td>
      
      <% if contribution.user.id == current_user.id %>
          <td><%= link_to '閲覧', contribution %></td>
          <td><%= link_to '編集', edit_contribution_path(contribution) %></td>
          <td><%= link_to '削除', contribution, method: :delete, data: { confirm: '本当に削除して良いですか？?' } %></td>
        <% else %>
          <td><%= link_to '閲覧', contribution_path(contribution.id) %></td>
        <% end %>
    <tr>
    <% end %>
</table>

app/views/contributions/new.html.erb
<div class="title_back_edit">
  <h1>New Contribution～新規投稿～</h1>
</div>

<%= render 'form', contribution: @contribution %>

<div class="title_back_edit">
  <%= link_to 'Back', contributions_path %>
</div>

app/views/contributions/show.html.erb
<p id="notice"></p>

<div class="title_back_edit">
  <h1>投稿詳細</h1>
</div>

<div class="c_show">
  <p>
    <strong>タイトル:</strong>
    <%= @contribution.title %>
  </p>
  
  <p>
    <strong>カテゴリ:</strong>
    <%= @contribution.category %>
  </p>
  
  
  <p>
    <strong>概要:</strong>
    <%= @contribution.overview %>
  </p>
  
  <p>
    <strong>更新日:</strong>
    <%= @contribution.modified %>
  </p>
  
  <p class="img">
    <strong>Image:</strong>
    <%= image_tag @contribution.file %>
  </p>
</div>


<div class="title_back_edit">

<%= link_to '戻る', contributions_path %>

  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(contribution_id: @contribution.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(contribution_id: @contribution.id), method: :post, class: 'btn btn-primary' %>
  <% end %>

</div>
  

app/views/favorites/crate.html.erb
<h1>Favorites#crate</h1>
<p>Find me in app/views/favorites/crate.html.erb</p>

app/views/favorites/index.html.erb
<div class="title_back_edit">
  <h1>favorites～ウォッチリスト～</h1>
</div>

<table border="1" bordercolor="#D8D8D8">
  <tr>
    <th>投稿者</th>
    <th>タイトル</th>
    <th>概要</th>
　　<th>カテゴリ</th>
    <th>更新日</th>
  </tr>

<% @favorites.each do |favorite| %>
  <tr>
    <% favorite.user.id == current_user.id %>
      <td><%= favorite.contribution.user.name %></td>
      <td><%= favorite.contribution.title %></td>
      <td><%= favorite.contribution.overview %></td>
      <td><%= favorite.contribution.category %></td>
      <td><%= favorite.contribution.modified %></td>
  <tr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proposal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <header>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">

      </div>

    		<div class="collapse navbar-collapse" id="navbarEexample7">
          <ul class="nav navbar-nav">
            <br>
            <% if logged_in? %>
              <li><%= link_to_unless_current "提案書を探す", contributions_path %></li>
              <li><%= link_to "出品する", new_contribution_path%></li>
              <li><%= link_to_unless_current "ウォッチリスト", favorites_path(current_user.id) %></li>
              <li><%= link_to_unless_current "マイページ", user_path(current_user.id) %></li>
              <li><%= link_to_unless_current "ログアウト", session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li><%= link_to "会員登録", new_user_path %></li>
              <li><%= link_to "ログイン", new_session_path %></li>
            <% end %>
            
          </ul>
        </div>
      </div>
    </nav>          
  </header>

  <body>
    <%= yield %>
  </body>
  
  <footer>
    <%= "@2018 ProposalStation" %>
  </footer>
</html>

app/views/users/new.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="introduction">

      <h1 class="h1_user_new">あなたのミッションはその資料を作ることですか？<h1>
      <h4>資料は"作る"ものではなく"売買する"時代に。 <br>
          ProposalStationは、提案資料のセカンドマーケットプレイスです。</h4>
    
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>  
    
      <div class="form_new">  
        <h2>新規登録フォーム</h2>
        <%= form_with(model: @user, local: true) do |f| %>  
          <p class="form"><%= f.label :お名前 %></p>
          <%= f.text_field :name %>
        
          <p class="form"><%= f.label :Eメールアドレス %></p>
          <%= f.email_field :email %>
        
          <p class="form"><%= f.label :パスワード %></p>
          <%= f.password_field :password %>
        
          <p class="form"><%= f.label :確認用パスワード %></p>
          <%= f.password_field :password_confirmation %>
          <br>
          <br>
        
          <%= f.submit "ユーザー登録" %>
        <% end %>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="title_back_edit">
  <h1><%= @user.name %>さんのページ</h1>
  
  
  <h2><%= @user.name %>さんの投稿一覧</h2>
</div>

<table border="1">
    <tr>
      <th>タイトル</th>
      <th>概要</th>
      <th>更新日</th>
    </tr>
    
    <% @contributions.each do |contribution| %> 
    <tr>    
      <td><%= contribution.title %></td>
      <td><%= contribution.overview %></td>
      <td><%= contribution.modified %></td>
  
      <% if @user.id == current_user.id %>
          <td><%= link_to '閲覧', contribution %></td>
          <td><%= link_to '編集', edit_contribution_path(contribution) %></td>
          <td><%= link_to '削除', contribution, method: :delete, data: { confirm: '本当に削除して良いですか？?' } %></td>
      <% else %>
          <td><%= contribution.title %></td>
          <td><%= link_to '閲覧', contribution_path(contribution.id) %></td>
          <td>なんでもいい</td>
      <% end %>   
    </tr>
    <% end %>
</table>